RDKCMF-8835 RDKV4.0 - [CMF] CMF cobalt build failure when gst update to 1.18.
when gstreamer update to 1.18, below error popped up.
../../third_party/starboard/rdk/shared/player/player_internal.cc:654:14: error: 'GST_VIDEO_TRANSFER_SMPTE_ST_2084' was not declared in this scope; did you mean 'GST_VIDEO_TRANSFER_SMPTE2084'?

The corresponding definition is in
gstreamer1.0-plugins-base/1.18.6-r0/image/usr/include/gstreamer-1.0/gst/video/video-color.h

Change-Id: If2451b70ed9992a8f36317c793b1395517b832bb
(cherry picked from commit c0ba0fc35ae9c4e78ba662b64d3b714acf169bb0)